### ISSUE TITLE
new file format and linter

### ISSUE THREAD

**Issue by icepuma** [RawkodeAcademy/content-management#1]
- [x] ~establish a new file format based on https://kdl.dev/~
- [x] ~adopt https://github.com/tailhook/knuffel to create a linter~
- [x] ~migrate existing YAMLs to KDL format~
- [x] use hcl

**Comment by rawkode** [comment]
I think KDL is great, but as @icepuma has worked in this signs of it being immature have shown, specifically around a lack of authoring tooling (no formatter). 

As the language we use to describe content isn’t something either of us are really tied down too, we want to remain flexible if another contender makes sense. 

Benefits:
- Mature tooling
  - https://hclq.sh/
- Editor support
- wouldn’t enforce a specified directory structure as types are named

As such, we’ll explore HCL in due course. 

- [x] Confirm if HCL tooling makes it a better authoring language

Are there any others we should experiment with during the holidays?
